apiVersion: v1
kind: ReplicationController
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    tier: web-server
  template:
    metadata:
      name: nginx
      labels:
        tier: web-server
    spec:
      containers:
      - name: web-server
        image: nginx
